# model.User login.
login: admin
# model.User  password.
password: admin


database:
  # the name of your JDBC driver
  driverClass: com.mysql.cj.jdbc.Driver

  # the username
  user: admin

  # the password
  password: admin

  # the JDBC URL
  url: jdbc:mysql://localhost:3306/dropwizard_test

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    # validate | update | create | create-drop
    hibernate.hbm2ddl.auto: validate

    maxWaitForConnection: 1s
    validationQuery: "/* Health Check */ SELECT 1"
    minSize: ${database.connections.min}
    maxSize: ${database.connections.max}
    checkConnectionWhileIdle: false
    checkConnectionOnBorrow: true
    checkConnectionOnReturn: true
    initialSize: ${database.connections.min}